'use client';
import { useState } from 'react';

export default function BookingPage(){
 const [form,setForm]=useState({customerName:'',phone:'',email:'',packageName:'',destination:'',travelDate:'',travellers:1,duration:'',notes:''});
 const [done,setDone]=useState(''); const [busy,setBusy]=useState(false);
 const set=(k,v)=>setForm(x=>({...x,[k]:v}));
 async function submit(e){e.preventDefault();setBusy(true);try{const r=await fetch('/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to submit');setDone(d.quotationNumber);setForm({customerName:'',phone:'',email:'',packageName:'',destination:'',travelDate:'',travellers:1,duration:'',notes:''});}catch(e){alert(e.message)}finally{setBusy(false)}}
 return <main style={{minHeight:'100vh',padding:'50px 20px',background:'#f8f6f1'}}><div style={{maxWidth:760,margin:'0 auto',background:'#fff',padding:32,borderRadius:20,boxShadow:'0 12px 40px rgba(0,0,0,.08)'}}><h1>Plan Your Trip</h1><p>Send your travel requirement to Touristaa. Our team will contact you with a quotation.</p>{done?<div style={{padding:24,borderRadius:14,background:'#f2f7ee'}}><h2>Request received ✓</h2><p>Your request number is <strong>{done}</strong>.</p><a href="/">Back to website</a></div>:<form onSubmit={submit} style={{display:'grid',gap:14}}><input required placeholder="Customer name" value={form.customerName} onChange={e=>set('customerName',e.target.value)}/><input required placeholder="Phone number" value={form.phone} onChange={e=>set('phone',e.target.value)}/><input type="email" placeholder="Email" value={form.email} onChange={e=>set('email',e.target.value)}/><input placeholder="Package / tour name" value={form.packageName} onChange={e=>set('packageName',e.target.value)}/><input placeholder="Destination" value={form.destination} onChange={e=>set('destination',e.target.value)}/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14}}><input type="date" value={form.travelDate} onChange={e=>set('travelDate',e.target.value)}/><input type="number" min="1" value={form.travellers} onChange={e=>set('travellers',e.target.value)} placeholder="Travellers"/></div><input placeholder="Duration" value={form.duration} onChange={e=>set('duration',e.target.value)}/><textarea rows="5" placeholder="Requirements, hotel preference, transport, inclusions etc." value={form.notes} onChange={e=>set('notes',e.target.value)}/><button disabled={busy} style={{padding:14,border:0,borderRadius:10,cursor:'pointer'}}>{busy?'Sending...':'Request a Quotation'}</button></form>}</div></main>
}
