'use client';
import './admin.css';
import {useEffect,useMemo,useState} from 'react';

const emptyPackage={name:'',destination:'',price:'',duration:'',description:'',category:'Domestic Tour',image:'',featured:false,active:true};
const emptyLead={name:'',phone:'',email:'',destination:'',message:'',status:'new',priority:'medium',source:'website',notes:'',followUpDate:'',assignedTo:'',budget:'',travelDate:''};
const emptyGallery={src:'',title:'',kind:'Ayodhya highlight',active:true};
const emptyTestimonial={name:'',text:'',rating:5,active:true};
const emptyFaq={question:'',answer:'',active:true};
const emptySettings={companyName:'Touristaa Travel Company',phone:'6387200498',email:'touristaaofficial@gmail.com',address:'Near Maharishi Valmiki International Airport, Ayodhya, Uttar Pradesh',heroEyebrow:'Explore the World With Us',heroTitle:'DISCOVER. EXPLORE. EXPERIENCE.',heroDescription:'Touristaa Travel Company is your trusted travel partner for memorable journeys, customized tours and comfortable travel experiences.',aboutTitle:'Your journey, our responsibility.',aboutText:'Touristaa Travel Company creates memorable, safe and hassle-free travel experiences.',mapQuery:'Near Maharishi Valmiki International Airport, Ayodhya, Uttar Pradesh',services:[],gallery:[],testimonials:[],faqs:[],stats:[],seo:{title:'Touristaa Travel Company | Ayodhya Tours & Travel',description:'Touristaa Travel Company offers customized tours, holiday packages and travel services from Ayodhya.',keywords:'Ayodhya tour, travel agency Ayodhya, Touristaa, tour packages'}};

async function fileToImageData(file){
 if(!file) return '';
 if(!file.type.startsWith('image/')) throw new Error('Please select an image file.');
 if(file.size>12*1024*1024) throw new Error('Image is too large. Please choose an image below 12 MB.');
 return await new Promise((resolve,reject)=>{
  const reader=new FileReader();
  reader.onerror=()=>reject(new Error('Unable to read image.'));
  reader.onload=()=>{
   const img=new Image();
   img.onload=()=>{
    const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height));
    const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));
    const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0,canvas.width,canvas.height);
    resolve(canvas.toDataURL('image/webp',0.82));
   };
   img.onerror=()=>reject(new Error('Invalid image file.'));img.src=reader.result;
  };
  reader.readAsDataURL(file);
 });
}

export default function Admin(){
 const [tab,setTab]=useState('dashboard'),[siteSection,setSiteSection]=useState('contact');
 const [packages,setPackages]=useState([]),[leads,setLeads]=useState([]),[settings,setSettings]=useState(emptySettings);
 const [form,setForm]=useState(emptyPackage),[lead,setLead]=useState(emptyLead),[galleryForm,setGalleryForm]=useState(emptyGallery),[testimonialForm,setTestimonialForm]=useState(emptyTestimonial),[faqForm,setFaqForm]=useState(emptyFaq);
 const [editing,setEditing]=useState(null),[editingLead,setEditingLead]=useState(null),[editingGallery,setEditingGallery]=useState(null),[editingTestimonial,setEditingTestimonial]=useState(null),[editingFaq,setEditingFaq]=useState(null);
 const [search,setSearch]=useState(''),[statusFilter,setStatusFilter]=useState('all'),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[uploading,setUploading]=useState(false);

 async function load(){
  setLoading(true);
  try{
   const [p,e,s]=await Promise.all([fetch('/api/admin/packages').then(r=>r.json()),fetch('/api/admin/enquiries').then(r=>r.json()),fetch('/api/admin/settings').then(r=>r.json())]);
   if([p,e,s].some(x=>x.error==='Unauthorized.')){window.location.href='/admin/login';return;}
   setPackages(p.packages||[]);setLeads(e.enquiries||[]);setSettings({...emptySettings,...(s.settings||{}),seo:{...emptySettings.seo,...(s.settings?.seo||{})}});
  }catch(err){console.error(err);notify('Unable to load admin data.');}finally{setLoading(false);}
 }
 useEffect(()=>{load()},[]);
 function notify(x){setMessage(x);setTimeout(()=>setMessage(''),3500)}
 const filteredLeads=useMemo(()=>leads.filter(l=>(statusFilter==='all'||l.status===statusFilter)&&[l.name,l.phone,l.email,l.destination,l.source].join(' ').toLowerCase().includes(search.toLowerCase())),[leads,statusFilter,search]);
 const counts={new:leads.filter(x=>x.status==='new').length,follow:leads.filter(x=>x.status==='follow-up').length,converted:leads.filter(x=>x.status==='converted').length};

 async function savePackage(e){
  e.preventDefault();setSaving(true);
  try{const r=await fetch('/api/admin/packages',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing?{id:editing,...form}:form)});const data=await r.json();if(!r.ok){alert(data.error||'Save failed');return;}setForm(emptyPackage);setEditing(null);notify(editing?'Package updated':'Package added');await load();}
  finally{setSaving(false);}
 }
 async function deletePackage(id){if(!confirm('Delete this tour package permanently?'))return;const r=await fetch('/api/admin/packages',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});if(r.ok){notify('Package deleted');load()}else alert((await r.json()).error||'Delete failed')}
 function editPackage(p){setEditing(p._id);setForm({name:p.name||'',destination:p.destination||'',price:p.price||'',duration:p.duration||'',description:p.description||'',category:p.category||'Domestic Tour',image:p.image||'',featured:!!p.featured,active:p.active!==false});setTab('packages');window.scrollTo({top:0,behavior:'smooth'})}
 async function handlePackageImage(e){try{setUploading(true);const src=await fileToImageData(e.target.files?.[0]);if(src)setForm(f=>({...f,image:src}));}catch(err){alert(err.message)}finally{setUploading(false);e.target.value=''}}

 async function saveLead(e){e.preventDefault();setSaving(true);try{const r=await fetch('/api/admin/enquiries',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:editingLead,...lead})});if(!r.ok){alert((await r.json()).error||'Save failed');return;}setEditingLead(null);setLead(emptyLead);notify('Lead updated');await load()}finally{setSaving(false)}}
 async function deleteLead(id){if(!confirm('Delete this customer lead?'))return;const r=await fetch('/api/admin/enquiries',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});if(r.ok)load();else alert((await r.json()).error||'Delete failed')}
 function editLead(l){setEditingLead(l._id);setLead({...emptyLead,...l,followUpDate:l.followUpDate?String(l.followUpDate).slice(0,10):'',travelDate:l.travelDate?String(l.travelDate).slice(0,10):''});setTab('crm')}

 async function saveSettings(e){e.preventDefault();setSaving(true);try{const r=await fetch('/api/admin/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(settings)});const data=await r.json();if(!r.ok){alert(data.error||'Settings save failed');return;}notify('Website content saved successfully');setSettings({...emptySettings,...(data.settings||settings),seo:{...emptySettings.seo,...((data.settings||settings).seo||{})}});}finally{setSaving(false)}}
 function updateService(i,key,value){const arr=[...(settings.services||[])];arr[i]={...(arr[i]||{}),[key]:value};setSettings({...settings,services:arr})}
 function updateArray(key,index,value){const arr=[...(settings[key]||[])];arr[index]=value;setSettings({...settings,[key]:arr})}
 function removeArray(key,index){setSettings({...settings,[key]:(settings[key]||[]).filter((_,i)=>i!==index)})}
 function addOrUpdate(key,value,setForm,setEditing,index){const arr=[...(settings[key]||[])];if(index!==null)arr[index]=value;else arr.push(value);setSettings({...settings,[key]:arr});setForm(key==='gallery'?emptyGallery:key==='testimonials'?emptyTestimonial:emptyFaq);setEditing(null)}
 async function saveGallery(e){e.preventDefault();await saveSettings(e);}
 async function handleGalleryFile(e){try{setUploading(true);const src=await fileToImageData(e.target.files?.[0]);if(src)setGalleryForm(f=>({...f,src}));}catch(err){alert(err.message)}finally{setUploading(false);e.target.value=''}}

 return <div className="admin">
  <div className="adminNav"><img src="/touristaa-logo.svg" alt="Touristaa Travel Company" className="adminLogo"/><div className="adminNavRight"><a href="/">View Website ↗</a><a href="/admin/login">Logout</a></div></div>
  <div className="dashboard"><div className="adminLayout">
   <aside className="adminSidebar"><h3>Touristaa CRM</h3>{[['dashboard','📊 Dashboard'],['crm','👥 Customer CRM'],['packages','🧳 Tour Packages'],['website','🖥️ Website Content']].map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{label}</button>)}</aside>
   <main className="adminMain">
    <div className="adminHeader"><div><div className="eyebrow">Admin / {tab}</div><h1>{tab==='dashboard'?'Business Dashboard':tab==='crm'?'Customer CRM':tab==='packages'?'Tour Package Manager':'Website Content Manager'}</h1></div>{message&&<div className="saveNotice">✓ {message}</div>}</div>

    {tab==='dashboard'&&<><div className="dashCards"><div className="dashCard">New Leads<strong>{counts.new}</strong></div><div className="dashCard">Follow-ups<strong>{counts.follow}</strong></div><div className="dashCard">Converted<strong>{counts.converted}</strong></div><div className="dashCard">Active Tours<strong>{packages.filter(p=>p.active!==false).length}</strong></div></div><section className="table"><div className="sectionHead"><h2>Recent Leads</h2><button className="outlineBtn" onClick={()=>setTab('crm')}>Open CRM →</button></div>{leads.slice(0,8).map(l=><div className="crmRow" key={l._id}><div><strong>{l.name}</strong><span>{l.destination||'General enquiry'} · {l.phone}</span></div><span className={`status ${l.status}`}>{l.status}</span><button onClick={()=>editLead(l)}>Manage</button></div>)}</section></>}

    {tab==='crm'&&<><section className="table"><div className="crmToolbar"><input placeholder="Search customer, phone, destination..." value={search} onChange={e=>setSearch(e.target.value)}/><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">All statuses</option><option value="new">New</option><option value="contacted">Contacted</option><option value="follow-up">Follow-up</option><option value="converted">Converted</option><option value="closed">Closed</option></select></div>{loading?<p>Loading...</p>:filteredLeads.map(l=><div className="crmRow" key={l._id}><div><strong>{l.name}</strong><span>{l.phone} · {l.email||'No email'} · {l.destination||'General'}</span></div><span className={`status ${l.status}`}>{l.status}</span><span>{l.followUpDate?new Date(l.followUpDate).toLocaleDateString():'—'}</span><button onClick={()=>editLead(l)}>Edit</button><button onClick={()=>deleteLead(l._id)}>Delete</button></div>)}</section>{editingLead&&<section className="table"><h2>Lead Details & Follow-up</h2><form className="adminForm" onSubmit={saveLead}><div className="formGrid"><input required value={lead.name} onChange={e=>setLead({...lead,name:e.target.value})} placeholder="Customer name"/><input required value={lead.phone} onChange={e=>setLead({...lead,phone:e.target.value})} placeholder="Phone"/><input type="email" value={lead.email} onChange={e=>setLead({...lead,email:e.target.value})} placeholder="Email"/><input value={lead.destination} onChange={e=>setLead({...lead,destination:e.target.value})} placeholder="Destination"/><input value={lead.budget} onChange={e=>setLead({...lead,budget:e.target.value})} placeholder="Budget"/><input type="date" value={lead.travelDate} onChange={e=>setLead({...lead,travelDate:e.target.value})}/><select value={lead.status} onChange={e=>setLead({...lead,status:e.target.value})}><option>new</option><option>contacted</option><option>follow-up</option><option>converted</option><option>closed</option></select><select value={lead.priority} onChange={e=>setLead({...lead,priority:e.target.value})}><option>low</option><option>medium</option><option>high</option></select><input type="date" value={lead.followUpDate} onChange={e=>setLead({...lead,followUpDate:e.target.value})}/><input value={lead.assignedTo} onChange={e=>setLead({...lead,assignedTo:e.target.value})} placeholder="Assigned to"/></div><textarea value={lead.message} onChange={e=>setLead({...lead,message:e.target.value})} placeholder="Customer requirement / enquiry"></textarea><textarea value={lead.notes} onChange={e=>setLead({...lead,notes:e.target.value})} placeholder="Internal CRM notes / follow-up notes"></textarea><button className="btn primary" disabled={saving}>Save Lead</button></form></section>}</>}

    {tab==='packages'&&<><section className="table"><h2>{editing?'Edit Existing Tour Package':'Add Tour Package'}</h2><form onSubmit={savePackage} className="adminForm"><div className="formGrid"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Package name"/><input required value={form.destination} onChange={e=>setForm({...form,destination:e.target.value})} placeholder="Destination / places"/><input required type="number" min="0" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} placeholder="Price"/><input required value={form.duration} onChange={e=>setForm({...form,duration:e.target.value})} placeholder="Duration"/><input value={form.image} onChange={e=>setForm({...form,image:e.target.value})} placeholder="Image URL (or upload below)"/><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Domestic Tour</option><option>International Tour</option><option>Educational Tour</option><option>Honeymoon Package</option><option>Family Trip</option><option>Corporate Tour</option></select></div><label className="uploadBox"><strong>📷 Package image from your device</strong><input type="file" accept="image/*" onChange={handlePackageImage}/><small>{uploading?'Processing image...':'Choose an image from your computer/mobile. It will be resized automatically.'}</small></label>{form.image&&<img src={form.image} alt="Package preview" style={{width:180,height:110,objectFit:'cover',borderRadius:12}}/>}<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Full description, day-wise itinerary, inclusions, exclusions, hotel, transport, notes..."/><label><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Featured package</label><label><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Show on website</label><button className="btn primary" disabled={saving||uploading}>{editing?'Update Package':'Add Package'}</button>{editing&&<button type="button" className="outlineBtn" onClick={()=>{setEditing(null);setForm(emptyPackage)}}>Cancel</button>}</form></section><section className="table"><h2>Existing Packages — Edit / Delete</h2>{packages.map(p=><div className="crmRow" key={p._id}>{p.image&&<img src={p.image} alt="" style={{width:72,height:52,objectFit:'cover',borderRadius:8}}/>}<div><strong>{p.name}</strong><span>{p.destination} · {p.duration} · ₹{Number(p.price||0).toLocaleString('en-IN')}</span></div><span>{p.active===false?'Hidden':'Live'}</span><button onClick={()=>editPackage(p)}>Edit</button><button onClick={()=>deletePackage(p._id)}>Delete</button></div>)}</section></>}

    {tab==='website'&&<><div className="crmToolbar" style={{marginBottom:16}}>{[['contact','Contact'],['homepage','Homepage / About'],['services','Services'],['gallery','Gallery'],['testimonials','Testimonials'],['faqs','FAQs'],['seo','SEO']].map(([id,label])=><button key={id} className={siteSection===id?'active':''} onClick={()=>setSiteSection(id)}>{label}</button>)}</div>
      {siteSection==='contact'&&<section className="table"><form onSubmit={saveSettings} className="adminForm"><h2>Company & Contact</h2><div className="formGrid"><input value={settings.companyName} onChange={e=>setSettings({...settings,companyName:e.target.value})} placeholder="Company name"/><input value={settings.phone} onChange={e=>setSettings({...settings,phone:e.target.value})} placeholder="Phone"/><input value={settings.email} onChange={e=>setSettings({...settings,email:e.target.value})} placeholder="Email"/><input value={settings.address} onChange={e=>setSettings({...settings,address:e.target.value})} placeholder="Address"/><input value={settings.mapQuery} onChange={e=>setSettings({...settings,mapQuery:e.target.value})} placeholder="Google Maps location"/></div><button className="btn primary" disabled={saving}>Save Contact & Map</button></form></section>}
      {siteSection==='homepage'&&<section className="table"><form onSubmit={saveSettings} className="adminForm"><h2>Homepage & About Us</h2><input value={settings.heroEyebrow} onChange={e=>setSettings({...settings,heroEyebrow:e.target.value})} placeholder="Hero eyebrow"/><input value={settings.heroTitle} onChange={e=>setSettings({...settings,heroTitle:e.target.value})} placeholder="Hero title"/><textarea value={settings.heroDescription} onChange={e=>setSettings({...settings,heroDescription:e.target.value})} placeholder="Hero description"/><input value={settings.aboutTitle} onChange={e=>setSettings({...settings,aboutTitle:e.target.value})} placeholder="About title"/><textarea value={settings.aboutText} onChange={e=>setSettings({...settings,aboutText:e.target.value})} placeholder="About text"/><h3>Business Stats</h3>{(settings.stats||[]).map((s,i)=><div className="formGrid" key={i}><input value={s.value||''} onChange={e=>updateArray('stats',i,{...s,value:e.target.value})} placeholder="Value"/><input value={s.label||''} onChange={e=>updateArray('stats',i,{...s,label:e.target.value})} placeholder="Label"/><button type="button" onClick={()=>removeArray('stats',i)}>Delete</button></div>)}<button type="button" className="outlineBtn" onClick={()=>setSettings({...settings,stats:[...(settings.stats||[]),{value:'',label:''}]})}>+ Add Stat</button><br/><button className="btn primary" disabled={saving}>Save Homepage Content</button></form></section>}
      {siteSection==='services'&&<section className="table"><form onSubmit={saveSettings} className="adminForm"><h2>Services</h2>{(settings.services||[]).map((s,i)=><div className="serviceEdit" key={i}><input value={s.icon||''} onChange={e=>updateService(i,'icon',e.target.value)} placeholder="Icon"/><input value={s.title||''} onChange={e=>updateService(i,'title',e.target.value)} placeholder="Service title"/><input value={s.description||''} onChange={e=>updateService(i,'description',e.target.value)} placeholder="Description"/><button type="button" onClick={()=>removeArray('services',i)}>Delete</button></div>)}<button type="button" className="outlineBtn" onClick={()=>setSettings({...settings,services:[...(settings.services||[]),{icon:'✨',title:'New Service',description:'Service description'}]})}>+ Add Service</button><br/><button className="btn primary" disabled={saving}>Save Services</button></form></section>}
      {siteSection==='gallery'&&<section className="table"><h2>Gallery Manager — Add / Edit / Delete</h2><form className="adminForm" onSubmit={saveGallery}><div className="formGrid"><input value={galleryForm.src} onChange={e=>setGalleryForm({...galleryForm,src:e.target.value})} placeholder="Image URL (optional if uploading)"/><input value={galleryForm.title} onChange={e=>setGalleryForm({...galleryForm,title:e.target.value})} placeholder="Photo title"/><input value={galleryForm.kind} onChange={e=>setGalleryForm({...galleryForm,kind:e.target.value})} placeholder="Category"/></div><label className="uploadBox"><strong>📷 Upload photo from your device</strong><input type="file" accept="image/*" onChange={handleGalleryFile}/><small>{uploading?'Processing image...':'Select JPG, PNG, WEBP or another image from your device.'}</small></label>{galleryForm.src&&<img src={galleryForm.src} alt="Gallery preview" style={{width:220,height:140,objectFit:'cover',borderRadius:12}}/>}<label><input type="checkbox" checked={galleryForm.active} onChange={e=>setGalleryForm({...galleryForm,active:e.target.checked})}/> Show photo on website</label><button type="submit" className="btn primary" disabled={saving||uploading}>{editingGallery!==null?'Update Photo':'Add Photo'}</button>{editingGallery!==null&&<button type="button" className="outlineBtn" onClick={()=>{setEditingGallery(null);setGalleryForm(emptyGallery)}}>Cancel</button>}</form>{(settings.gallery||[]).map((g,i)=><div className="crmRow" key={i}><img src={g.src} alt="" style={{width:72,height:52,objectFit:'cover',borderRadius:8}}/><div><strong>{g.title||'Untitled photo'}</strong><span>{g.kind} · {g.active===false?'Hidden':'Live'}</span></div><button onClick={()=>{setEditingGallery(i);setGalleryForm({...emptyGallery,...g})}}>Edit</button><button onClick={()=>{removeArray('gallery',i)}}>Delete</button></div>)}</section>}
      {siteSection==='testimonials'&&<section className="table"><h2>Testimonials Manager</h2><div className="adminForm"><div className="formGrid"><input value={testimonialForm.name} onChange={e=>setTestimonialForm({...testimonialForm,name:e.target.value})} placeholder="Customer name"/><input type="number" min="1" max="5" value={testimonialForm.rating} onChange={e=>setTestimonialForm({...testimonialForm,rating:e.target.value})} placeholder="Rating"/></div><textarea value={testimonialForm.text} onChange={e=>setTestimonialForm({...testimonialForm,text:e.target.value})} placeholder="Customer review"/><button type="button" className="btn primary" onClick={()=>addOrUpdate('testimonials',testimonialForm,setTestimonialForm,setEditingTestimonial,editingTestimonial)}> {editingTestimonial!==null?'Update Review':'Add Review'}</button><button type="button" className="btn primary" onClick={()=>saveSettings({preventDefault(){}})}>Save Testimonials</button></div>{(settings.testimonials||[]).map((t,i)=><div className="crmRow" key={i}><div><strong>{t.name}</strong><span>★ {t.rating} · {t.text}</span></div><button onClick={()=>{setEditingTestimonial(i);setTestimonialForm(t)}}>Edit</button><button onClick={()=>removeArray('testimonials',i)}>Delete</button></div>)}</section>}
      {siteSection==='faqs'&&<section className="table"><h2>FAQ Manager</h2><div className="adminForm"><input value={faqForm.question} onChange={e=>setFaqForm({...faqForm,question:e.target.value})} placeholder="Question"/><textarea value={faqForm.answer} onChange={e=>setFaqForm({...faqForm,answer:e.target.value})} placeholder="Answer"/><button type="button" className="btn primary" onClick={()=>addOrUpdate('faqs',faqForm,setFaqForm,setEditingFaq,editingFaq)}>{editingFaq!==null?'Update FAQ':'Add FAQ'}</button><button type="button" className="btn primary" onClick={()=>saveSettings({preventDefault(){}})}>Save FAQs</button></div>{(settings.faqs||[]).map((f,i)=><div className="crmRow" key={i}><div><strong>{f.question}</strong><span>{f.answer}</span></div><button onClick={()=>{setEditingFaq(i);setFaqForm(f)}}>Edit</button><button onClick={()=>removeArray('faqs',i)}>Delete</button></div>)}</section>}
      {siteSection==='seo'&&<section className="table"><form onSubmit={saveSettings} className="adminForm"><h2>SEO Settings</h2><input value={settings.seo.title} onChange={e=>setSettings({...settings,seo:{...settings.seo,title:e.target.value}})} placeholder="SEO title"/><textarea value={settings.seo.description} onChange={e=>setSettings({...settings,seo:{...settings.seo,description:e.target.value}})} placeholder="Meta description"/><input value={settings.seo.keywords} onChange={e=>setSettings({...settings,seo:{...settings.seo,keywords:e.target.value}})} placeholder="Keywords"/><button className="btn primary" disabled={saving}>Save SEO</button></form></section>}
    </>}
   </main>
  </div></div>
 </div>
}
