'use client';
import {useEffect,useState} from 'react';
const PHONE='6387200498',PHONE_DISPLAY='+91 63872 00498',EMAIL='touristaaofficial@gmail.com';
const WHATSAPP=`https://wa.me/916387200498?text=${encodeURIComponent('Hello Touristaa Travel Company, I would like to enquire about a tour package.')}`;
const fallbackServices=[['✈️','Domestic Tours','Explore India with carefully planned itineraries and comfortable travel.'],['🌍','International Tours','Discover destinations worldwide with customized travel packages.'],['🎓','Educational Tours','Safe, engaging tours for schools, colleges and student groups.'],['💍','Honeymoon Packages','Romantic getaways designed around your dates and preferences.'],['👨‍👩‍👧','Family Trips','Flexible family holidays with comfortable stays and transport.'],['🏢','Corporate Tours','Reliable group travel, retreats and corporate arrangements.']];
const fallbackTours=[['Varanasi Educational Tour','1 Day','2200','BHU • Kashi Vishwanath • Assi Ghat • Ganga Aarti','https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=900&q=80'],['Manali Escape','3 Days / 2 Nights','6999','Mountains • Local sightseeing • Comfortable stay','https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=900&q=80'],['Kerala Backwaters','4 Days / 3 Nights','9999','Munnar • Alleppey • Kochi','https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=900&q=80'],['Goa Beach Vacation','3 Days / 2 Nights','7999','Beaches • Local sightseeing • Leisure','https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=900&q=80']];
const fallbackGallery=[{src:'/gallery-touristaa-01.jpg',title:'Touristaa customer group at Ayodhya',kind:'Touristaa customer photo'},{src:'https://commons.wikimedia.org/wiki/Special:FilePath/Ayodhya_Diwali_2021_01.jpg?width=1400',title:'Ayodhya Deepotsav at Ram Ki Paidi',kind:'Deepotsav'},{src:'https://commons.wikimedia.org/wiki/Special:FilePath/Ram_Ki_Paidi_waterfront.jpg?width=1400',title:'Ram Ki Paidi waterfront in daylight',kind:'Ghat • Daytime'},{src:'https://commons.wikimedia.org/wiki/Special:FilePath/Saryu_Ghat_Arti.jpg?width=1400',title:'Saryu Ghat evening Aarti',kind:'Ghat • Aarti'}];
const defaults={companyName:'Touristaa Travel Company',phone:PHONE,email:EMAIL,address:'Near Maharishi Valmiki International Airport, Ayodhya, Uttar Pradesh',heroEyebrow:'Explore the World With Us',heroTitle:'DISCOVER. EXPLORE. EXPERIENCE.',heroDescription:'Touristaa Travel Company is your trusted travel partner for memorable journeys, customized tours and comfortable travel experiences.',aboutTitle:'Your journey, our responsibility.',aboutText:'Touristaa Travel Company creates memorable, safe and hassle-free travel experiences. We plan domestic and international holidays, educational tours, honeymoon trips, family vacations and corporate travel with customer-focused support from enquiry to return.',mapQuery:'Near Maharishi Valmiki International Airport, Ayodhya, Uttar Pradesh',services:[],gallery:[],testimonials:[],faqs:[],stats:[]};
export default function Home(){
 const [packages,setPackages]=useState([]),[site,setSite]=useState(defaults),[form,setForm]=useState({name:'',phone:'',email:'',destination:'',message:''}),[sent,setSent]=useState(false);
 useEffect(()=>{Promise.all([fetch('/api/packages').then(r=>r.json()),fetch('/api/settings').then(r=>r.json())]).then(([p,s])=>{setPackages(p.packages||[]);setSite({...defaults,...s})}).catch(()=>{})},[]);
 const tours=packages.length?packages.map(p=>({id:p._id,name:p.name,duration:p.duration,price:`₹${Number(p.price||0).toLocaleString('en-IN')}`,places:p.destination,image:p.image||fallbackTours[0][4]})):fallbackTours.map(x=>({name:x[0],duration:x[1],price:`₹${Number(x[2]).toLocaleString('en-IN')}`,places:x[3],image:x[4]}));
 const services=site.services?.length?site.services.map(s=>[s.icon,s.title,s.description]):fallbackServices;
 const gallery=(site.gallery||[]).filter(g=>g.active!==false&&g.src).length?(site.gallery||[]).filter(g=>g.active!==false&&g.src):fallbackGallery;
 async function submit(e){e.preventDefault();const r=await fetch('/api/enquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});if(r.ok){setSent(true);setForm({name:'',phone:'',email:'',destination:'',message:''})}}
 return <><div className="topbar"><div className="container topbarInner"><span>📞 <a href={`tel:+91${site.phone}`}>{site.phone}</a> &nbsp; | &nbsp; ✉️ <a href={`mailto:${site.email}`}>{site.email}</a></span><span>{site.companyName} • Ayodhya</span></div></div>
 <header className="nav"><div className="container navInner"><a href="#home" className="logoWrap"><img src="/touristaa-logo.svg" alt={site.companyName} className="logo"/></a><nav className="links"><a href="#home">Home</a><a href="#about">About Us</a><a href="#packages">Tour Packages</a><a href="#services">Services</a><a href="#gallery">Gallery</a><a href="#contact">Contact Us</a></nav><a className="btn primary navBtn" href={WHATSAPP} target="_blank" rel="noreferrer">WhatsApp Enquiry</a></div></header>
 <main id="home"><section className="hero"><div className="container heroContent"><div className="heroCopy reveal"><div className="script">{site.heroEyebrow}</div><h1>{site.heroTitle}</h1><p>{site.heroDescription}</p><div className="heroActions"><a className="btn primary" href="#packages">Explore Packages</a><a className="btn lightBtn" href={`tel:+91${site.phone}`}>📞 Call Now</a></div><div className="heroStats">{(site.stats?.length?site.stats:[{value:'1000+',label:'Happy Customers'},{value:'5+',label:'Years of Excellence'},{value:'✓',label:'Safe & Comfortable'}]).slice(0,3).map((s,i)=><div key={i}><b>{s.value}</b><small>{s.label}</small></div>)}</div></div><div className="searchCard floatCard"><h2>Find Your <span>Perfect Trip</span></h2><input placeholder="📍 Where to?"/><select defaultValue=""><option value="" disabled>Select Tour Type</option><option>Domestic Tour</option><option>International Tour</option><option>Educational Tour</option><option>Honeymoon Package</option></select><div className="dateRow"><input type="date"/><input type="date"/></div><input placeholder="👥 Guests"/><a href="#packages" className="btn primary fullBtn">Search Packages</a></div></div></section>
 <section className="trustBar"><div><b>🏷️ Best Price</b><span>Value-focused packages</span></div><div><b>🎧 24/7 Support</b><span>We are here to help</span></div><div><b>☑️ Easy Booking</b><span>Hassle free planning</span></div><div><b>🛡️ Trusted Travel</b><span>Safe & comfortable</span></div></section>
 <section className="section" id="services"><div className="container"><div className="titleRow"><div><div className="eyebrow">Our <span>Services</span></div><h2>Travel solutions for every journey</h2></div></div><div className="serviceGrid">{services.map(([icon,title,text])=><article className="serviceCard animatedCard" key={title}><div className="serviceIcon">{icon}</div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
 <section className="section packagesSection" id="packages"><div className="container"><div className="titleRow"><div><div className="eyebrow">Popular Tour <span>Packages</span></div><h2>Choose your next adventure</h2></div><a className="outlineBtn" href="#contact">Plan a Custom Trip →</a></div><div className="packageGrid">{tours.map((p,i)=><article className="tourCard animatedCard" key={(p.id||p.name)+i}><img src={p.image} alt={p.name}/><div className="tourBody"><h3>{p.name}</h3><p>📍 {p.places}</p><p>◷ {p.duration}</p><strong>{p.price}<small> /Person</small></strong>{p.id&&<a className="outlineBtn" href={`/packages/${p.id}`}>View Full Package →</a>}<a href={WHATSAPP} target="_blank" rel="noreferrer">WhatsApp Enquiry →</a></div></article>)}</div></div></section>
 <section className="gallerySection section" id="gallery"><div className="container"><div className="titleRow"><div><div className="eyebrow">Ayodhya <span>Gallery</span></div><h2>Real Touristaa moments & Ayodhya highlights</h2><p className="sectionIntro">Selected memories on the homepage. Explore the complete collection.</p></div></div><div className="galleryGrid">{gallery.slice(0,4).map((g,i)=><a className={`galleryItem galleryItem${i+1}`} href="/gallery" key={g.src+i}><span style={{position:'relative',display:'block',height:'100%'}}><img src={g.src} alt={g.title} loading="lazy"/>{i===3&&<span style={{position:'absolute',inset:0,display:'flex',alignItems:'center',justifyContent:'center',background:'rgba(0,0,0,.48)',color:'#fff',fontSize:'1.35rem',fontWeight:800}}>+ More</span>}</span><span><b>{g.title}</b><small>{g.kind}</small></span></a>)}</div><div style={{textAlign:'center',marginTop:'22px'}}><a className="outlineBtn" href="/gallery">View Full Gallery →</a></div></div></section>
 <section className="aboutBand" id="about"><div className="container aboutGrid"><div><div className="eyebrow">About <span>Touristaa</span></div><h2>{site.aboutTitle}</h2><p>{site.aboutText}</p><a className="btn primary" href={WHATSAPP} target="_blank" rel="noreferrer">Plan My Trip on WhatsApp</a></div><div className="aboutPoints">{(site.stats?.length?site.stats:[{value:'1000+',label:'Customers'},{value:'5+',label:'Years of Experience'},{value:'Custom',label:'Packages'},{value:'24/7',label:'Support'}]).slice(0,4).map((s,i)=><div key={i}><b>{s.value}</b><span>{s.label}</span></div>)}</div></div></section>
 {site.testimonials?.filter(t=>t.active!==false).length>0&&<section className="section"><div className="container"><div className="titleRow"><div><div className="eyebrow">Customer <span>Reviews</span></div><h2>What our travellers say</h2></div></div><div className="serviceGrid">{site.testimonials.filter(t=>t.active!==false).map((t,i)=><article className="serviceCard" key={i}><div>★★★★★</div><p>“{t.text}”</p><strong>{t.name}</strong></article>)}</div></div></section>}
 {site.faqs?.filter(f=>f.active!==false).length>0&&<section className="section"><div className="container"><div className="titleRow"><div><div className="eyebrow">Travel <span>FAQs</span></div><h2>Frequently asked questions</h2></div></div><div className="serviceGrid">{site.faqs.filter(f=>f.active!==false).map((f,i)=><article className="serviceCard" key={i}><h3>{f.question}</h3><p>{f.answer}</p></article>)}</div></div></section>}
 <section className="section locationSection" id="location"><div className="container"><div className="titleRow"><div><div className="eyebrow">Find <span>Us</span></div><h2>Visit Touristaa Travel Company</h2><p className="sectionIntro">{site.address}</p></div><a className="outlineBtn" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(site.mapQuery||site.address)}`} target="_blank" rel="noreferrer">Open in Google Maps →</a></div><div className="mapCard"><iframe title="Touristaa Travel Company location map" src={`https://www.google.com/maps?q=${encodeURIComponent(site.mapQuery||site.address)}&output=embed`} loading="lazy" referrerPolicy="no-referrer-when-downgrade"></iframe></div></div></section>
 <section className="section contactSection" id="contact"><div className="container"><div className="contactBox"><div><div className="eyebrow">Let's plan your trip</div><h2>Tell us where you want to go.</h2><p>Share your destination and travel requirements. Our team will contact you with a customized package.</p><div className="contactQuick"><a href={`tel:+91${site.phone}`}>📞 <span>Call</span><b>{site.phone}</b></a><a href={WHATSAPP} target="_blank" rel="noreferrer">💬 <span>WhatsApp</span><b>Chat with us</b></a><a href={`mailto:${site.email}`}>✉️ <span>Email</span><b>{site.email}</b></a></div>{sent&&<p className="successMsg">✓ Enquiry sent successfully. We will contact you soon.</p>}</div><form onSubmit={submit}><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your name" required/><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Phone number" required/><input value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="Email address"/><input value={form.destination} onChange={e=>setForm({...form,destination:e.target.value})} placeholder="Destination"/><textarea value={form.message} onChange={e=>setForm({...form,message:e.target.value})} rows="4" placeholder="Tell us about your trip"></textarea><button className="btn primary" type="submit">Send Enquiry</button></form></div></div></section></main>
 <a className="callFloat" href={`tel:+91${site.phone}`} aria-label="Call Touristaa">📞</a><a className="whatsapp" href={WHATSAPP} target="_blank" rel="noreferrer" aria-label="WhatsApp Touristaa">💬</a><footer className="footer"><div className="container footerGrid"><div><img src="/touristaa-logo.svg" alt={site.companyName} className="footerLogo"/><p>Affordable, safe and comfortable travel experiences from Ayodhya.</p><p>📍 {site.address}</p></div><div><h4>Quick Links</h4><a href="#about">About Us</a><a href="#packages">Packages</a><a href="#services">Services</a><a href="/gallery">Gallery</a><a href="#contact">Contact</a></div><div><h4>Contact</h4><a href={`tel:+91${site.phone}`}>{site.phone}</a><a href={`mailto:${site.email}`}>{site.email}</a><a href={WHATSAPP} target="_blank" rel="noreferrer">WhatsApp</a></div><div><h4>Admin</h4><a href="/admin/login">Admin Login</a></div></div><div className="copyright">© 2026 {site.companyName}. All rights reserved.</div></footer></>
}
