'use client';
import {useEffect,useState} from 'react';

const empty={customerName:'',phone:'',email:'',packageName:'',destination:'',travelDate:'',travellers:1,duration:'',amount:0,advanceAmount:0,status:'quotation',paymentStatus:'unpaid',notes:'',quotationNumber:''};
const money=n=>`₹${Number(n||0).toLocaleString('en-IN')}`;
export default function BookingsAdmin(){
 const [items,setItems]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/admin/bookings');const d=await r.json();if(r.status===401){location.href='/admin/login';return}setItems(d.bookings||[])}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const change=(k,v)=>setForm(x=>({...x,[k]:v}));
 function edit(x){setEditing(x._id);setForm({...empty,...x,travelDate:x.travelDate?String(x.travelDate).slice(0,10):''})}
 async function save(e){e.preventDefault();setSaving(true);try{const r=await fetch('/api/admin/bookings',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing?{id:editing,...form}:form)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Save failed');setForm(empty);setEditing(null);await load()}catch(e){alert(e.message)}finally{setSaving(false)}}
 async function remove(id){if(!confirm('Delete this booking/quotation?'))return;await fetch('/api/admin/bookings',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});load()}
 function printQuote(x){const html=`<!doctype html><html><head><title>${x.quotationNumber||'Touristaa Quotation'}</title><style>body{font-family:Arial;padding:40px;max-width:800px;margin:auto}h1{margin-bottom:4px}.top{display:flex;justify-content:space-between;border-bottom:2px solid #222;padding-bottom:20px}.box{padding:18px;background:#f5f5f5;margin:22px 0}table{width:100%;border-collapse:collapse}td{padding:10px;border-bottom:1px solid #ddd}.total{font-size:20px;font-weight:bold}</style></head><body><div class="top"><div><h1>Touristaa Travel Company</h1><div>Ayodhya, Uttar Pradesh</div><div>6387200498 · touristaaofficial@gmail.com</div></div><div><strong>Quotation</strong><br>${x.quotationNumber||''}<br>${new Date(x.createdAt||Date.now()).toLocaleDateString('en-IN')}</div></div><div class="box"><strong>Customer</strong><br>${x.customerName}<br>${x.phone}${x.email?` · ${x.email}`:''}</div><table><tr><td>Tour / Package</td><td>${x.packageName||'Customized Trip'}</td></tr><tr><td>Destination</td><td>${x.destination||'—'}</td></tr><tr><td>Travel date</td><td>${x.travelDate?new Date(x.travelDate).toLocaleDateString('en-IN'):'—'}</td></tr><tr><td>Travellers</td><td>${x.travellers||1}</td></tr><tr><td>Duration</td><td>${x.duration||'—'}</td></tr><tr><td class="total">Total</td><td class="total">${money(x.amount)}</td></tr><tr><td>Advance</td><td>${money(x.advanceAmount)}</td></tr><tr><td>Balance</td><td>${money(Math.max(0,Number(x.amount||0)-Number(x.advanceAmount||0)))}</td></tr></table><div class="box">${x.notes||'Thank you for choosing Touristaa Travel Company.'}</div><script>window.print()</script></body></html>`;const w=window.open('','_blank');w.document.write(html);w.document.close()}
 return <main style={{padding:30,maxWidth:1250,margin:'auto',fontFamily:'Arial'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><a href="/admin">← Admin Dashboard</a><h1>Bookings & Quotations</h1><p>Convert travel requirements into quotations and confirmed bookings.</p></div><a href="/booking" target="_blank">Open customer booking form ↗</a></div><section style={{padding:22,border:'1px solid #ddd',borderRadius:16,margin:'24px 0'}}><h2>{editing?'Edit Booking / Quotation':'Create Booking / Quotation'}</h2><form onSubmit={save} style={{display:'grid',gap:12}}><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:12}}>{[['customerName','Customer name'],['phone','Phone'],['email','Email'],['packageName','Package / tour'],['destination','Destination'],['duration','Duration'],['travelDate','Travel date'],['travellers','Travellers'],['amount','Total amount'],['advanceAmount','Advance amount']].map(([k,p])=><input key={k} required={k==='customerName'||k==='phone'} type={k==='travelDate'?'date':k==='amount'||k==='advanceAmount'||k==='travellers'?'number':'text'} min={k==='travellers'?'1':k==='amount'||k==='advanceAmount'?'0':undefined} placeholder={p} value={form[k]||''} onChange={e=>change(k,e.target.value)}/>)}<select value={form.status} onChange={e=>change('status',e.target.value)}>{['quotation','pending','confirmed','completed','cancelled'].map(x=><option key={x}>{x}</option>)}</select><select value={form.paymentStatus} onChange={e=>change('paymentStatus',e.target.value)}>{['unpaid','partial','paid'].map(x=><option key={x}>{x}</option>)}</select></div><textarea rows="4" placeholder="Notes / inclusions / special requirements" value={form.notes} onChange={e=>change('notes',e.target.value)}/><button disabled={saving}>{saving?'Saving...':editing?'Update Booking':'Create Quotation'}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(empty)}}>Cancel</button>}</form></section><section><h2>All Bookings & Quotations</h2>{loading?<p>Loading...</p>:items.map(x=><article key={x._id} style={{display:'grid',gridTemplateColumns:'2fr 1fr 1fr 1fr auto auto auto',gap:12,alignItems:'center',padding:15,borderBottom:'1px solid #ddd'}}><div><strong>{x.customerName}</strong><div>{x.packageName||'Customized Trip'} · {x.destination}</div><small>{x.phone} · {x.quotationNumber}</small></div><span>{x.status}</span><span>{x.paymentStatus}</span><span>{money(x.amount)}</span><button onClick={()=>edit(x)}>Edit</button><button onClick={()=>printQuote(x)}>Print Quote</button><button onClick={()=>remove(x._id)}>Delete</button></article>)}</section></main>
}
